#build: `docker build -t atlas-plugin-docker-build  - < Dockerfile`
#debug: `docker run -it atlas-plugin-docker-build bash`
FROM java:8-jdk

# Maintainers on this project are the following:
MAINTAINER Thomas Whalen-Bridge <thomasjmwb@gmail.com>
#RUN sed -i '/jessie-updates/d' /etc/apt/sources.list  # Now archived
RUN ln -s /usr/lib/apt/methods/http /usr/lib/apt/methods/https 
#RUN ls -l /etc/apt/sources.list.d/
#RUN apt-get update



ADD http://sdkrepo.atlassian.com/deb-archive/atlassian-plugin-sdk_8.0.7_all.deb /amps.deb

# Install the Atlassian Plugins SDK using the official Aptitude debian
# package repository
RUN echo "deb http://sdkrepo.atlassian.com/debian/ stable contrib" >>/etc/apt/sources.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B07804338C015B73 \
#    && apt-get update \
#    && apt-get install apt-transport-https \
#    && apt-get update \
    && dpkg -i /amps.deb

# Copy Maven preference files to predefine the command line question about
# subscribing to the mailing list to `NO`.
#COPY .java /root/.java

# Create directory for sources using the same practice as the ruby images
#RUN mkdir -p /usr/src/app
#WORKDIR /usr/src/app

# Set the default running command of the AMPS image to be running the
# application in debug mode.
CMD ["atlas-version"]