#build: `docker build -t thomasjmwb/atlas-plugin-build  - < Dockerfile`
#debug: `docker run -it thomasjmwb/atlas-plugin-build bash`
FROM openjdk:8-jre

# Maintainers on this project are the following:
MAINTAINER Thomas Whalen-Bridge <thomasjmwb@gmail.com>

RUN apt-get update
RUN apt-get install apt-transport-https curl gnupg -yq 


# get install script and pass it to execute: 
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash
# and install node 
RUN apt-get install nodejs -yq
# confirm that it was successful 
RUN node -v
# npm installs automatically 
RUN npm -v


ADD http://sdkrepo.atlassian.com/deb-archive/atlassian-plugin-sdk_8.0.7_all.deb /amps.deb

# Install the Atlassian Plugins SDK using the official Aptitude debian
# package repository
RUN echo "deb http://sdkrepo.atlassian.com/debian/ stable contrib" >>/etc/apt/sources.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B07804338C015B73 \
    && dpkg -i /amps.deb



# Set the default running command of the AMPS image to be running the
# application in debug mode.
CMD ["atlas-version"]